/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multiprograms;

import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author efrai
 */
public class divisas extends javax.swing.JFrame {

    /**
     * Creates new form divisas
     */
    public divisas() {
        initComponents();
//        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloConDivisasJLabel = new javax.swing.JLabel();
        iconDivisasBlancoJLabel = new javax.swing.JLabel();
        monedaRightJLabel = new javax.swing.JLabel();
        numeroRightJTextField = new javax.swing.JTextField();
        iconDivisasJLabel = new javax.swing.JLabel();
        paisRightJComboBox = new javax.swing.JComboBox<>();
        monedaLeftJLabel = new javax.swing.JLabel();
        numeroLeftJTextField = new javax.swing.JTextField();
        paisLeftJComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 235));

        tituloConDivisasJLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloConDivisasJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloConDivisasJLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloConDivisasJLabel.setText("Conversor de Divisas");

        iconDivisasBlancoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-cambio-de-divisas-60-blaco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tituloConDivisasJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(iconDivisasBlancoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tituloConDivisasJLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconDivisasBlancoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 100));

        monedaRightJLabel.setBackground(new java.awt.Color(45, 118, 235));
        monedaRightJLabel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        monedaRightJLabel.setForeground(new java.awt.Color(45, 118, 235));
        monedaRightJLabel.setText("Moneda:");
        jPanel1.add(monedaRightJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 100, 20));

        numeroRightJTextField.setBackground(new java.awt.Color(255, 255, 255));
        numeroRightJTextField.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        numeroRightJTextField.setForeground(new java.awt.Color(45, 118, 235));
        numeroRightJTextField.setText("0.0");
        jPanel1.add(numeroRightJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 220, 40));

        iconDivisasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-cambio-de-divisas-60.png"))); // NOI18N
        jPanel1.add(iconDivisasJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        paisRightJComboBox.setBackground(new java.awt.Color(45, 118, 235));
        paisRightJComboBox.setForeground(new java.awt.Color(45, 118, 235));
        paisRightJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolares:USD", "Peso México:MXN", "Euro:EUR", "Libras Esterlinas:GBP", "Yenes:JPY" }));
        paisRightJComboBox.setToolTipText("");
        paisRightJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisRightJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(paisRightJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 220, 40));

        monedaLeftJLabel.setBackground(new java.awt.Color(45, 118, 235));
        monedaLeftJLabel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        monedaLeftJLabel.setForeground(new java.awt.Color(45, 118, 235));
        monedaLeftJLabel.setText("Moneda:");
        jPanel1.add(monedaLeftJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, 20));

        numeroLeftJTextField.setBackground(new java.awt.Color(255, 255, 255));
        numeroLeftJTextField.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        numeroLeftJTextField.setForeground(new java.awt.Color(45, 118, 235));
        numeroLeftJTextField.setText("0.0");
        numeroLeftJTextField.setToolTipText("");
        jPanel1.add(numeroLeftJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 220, 40));

        paisLeftJComboBox.setBackground(new java.awt.Color(45, 118, 235));
        paisLeftJComboBox.setForeground(new java.awt.Color(45, 118, 235));
        paisLeftJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolares:USD", "Peso México:MXN", "Euro:EUR", "Libras Esterlinas:GBP", "Yenes:JPY" }));
        paisLeftJComboBox.setToolTipText("Dolares:USD\nPeso México:MXN\nEuro:EUR\nLibras Esterlinas:GBP\nYenes:JPY\n");
        paisLeftJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisLeftJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(paisLeftJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paisLeftJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisLeftJComboBoxActionPerformed
        // TODO add your handling code here:
        String text = "";
        text =  numeroRightJTextField.getText();
       
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribe la unidad que desas, en el recuadro Izquierdo por favor");
        }else if(Funciones.validacionNumero(text)){
            double unidades = Double.parseDouble(text);
            String eleccion = paisLeftJComboBox.getSelectedItem().toString();
            String NomenclaturaElegida = FuncionesDivisas.retornaMoneda(eleccion);
             String convertir = paisRightJComboBox.getSelectedItem().toString();
             String NomenclaturaConvertir = FuncionesDivisas.retornaMoneda(convertir);
             
             double monedaConvertida = ApiRest.transformaMoneda(NomenclaturaConvertir, NomenclaturaElegida, unidades);
             String resultado = String.valueOf(monedaConvertida);
              numeroLeftJTextField.setText(resultado);
        }else{
               JOptionPane.showMessageDialog(null, "Solo se aceptan numeros, punto y el signo de menos");
        }
        
    }//GEN-LAST:event_paisLeftJComboBoxActionPerformed

    private void paisRightJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisRightJComboBoxActionPerformed
        // TODO add your handling code here:
           String text = "";
        text =  numeroLeftJTextField.getText();
       
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribe la unidad que desas, en el recuadro Derecha por favor");
        }else if(Funciones.validacionNumero(text)){
            double unidades = Double.parseDouble(text);
            String eleccion = paisLeftJComboBox.getSelectedItem().toString();
            String NomenclaturaElegida = FuncionesDivisas.retornaMoneda(eleccion);
             String convertir = paisRightJComboBox.getSelectedItem().toString();
             String NomenclaturaConvertir = FuncionesDivisas.retornaMoneda(convertir);
             
             double monedaConvertida = ApiRest.transformaMoneda(NomenclaturaElegida, NomenclaturaConvertir, unidades);
             String resultado = String.valueOf(monedaConvertida);
              numeroRightJTextField.setText(resultado);
        }else{
               JOptionPane.showMessageDialog(null, "Solo se aceptan numeros, punto y el signo de menos");
        }
    }//GEN-LAST:event_paisRightJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new divisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconDivisasBlancoJLabel;
    private javax.swing.JLabel iconDivisasJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel monedaLeftJLabel;
    private javax.swing.JLabel monedaRightJLabel;
    private javax.swing.JTextField numeroLeftJTextField;
    private javax.swing.JTextField numeroRightJTextField;
    private javax.swing.JComboBox<String> paisLeftJComboBox;
    private javax.swing.JComboBox<String> paisRightJComboBox;
    private javax.swing.JLabel tituloConDivisasJLabel;
    // End of variables declaration//GEN-END:variables
}
