/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multiprograms;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author efrai
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        menuJPanel = new javax.swing.JPanel();
        titleJPanel = new javax.swing.JPanel();
        tituloJLabel = new javax.swing.JLabel();
        esloganJLabel = new javax.swing.JLabel();
        exitJLabel = new javax.swing.JLabel();
        minimizeJLabel = new javax.swing.JLabel();
        masaJPanel = new javax.swing.JPanel();
        iconMasaJLabel = new javax.swing.JLabel();
        masaJLabel = new javax.swing.JLabel();
        divisasJPanel = new javax.swing.JPanel();
        iconDivisasJLabel = new javax.swing.JLabel();
        divisasJLabel = new javax.swing.JLabel();
        temperaturaJPanel = new javax.swing.JPanel();
        iconTemperaturaJLabel = new javax.swing.JLabel();
        temperaturaJLabel = new javax.swing.JLabel();
        longitudJPanel = new javax.swing.JPanel();
        iconLongitudJLabel = new javax.swing.JLabel();
        longitudJLabel = new javax.swing.JLabel();
        infoJLabel = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        menuJPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleJPanel.setBackground(new java.awt.Color(45, 118, 235));

        tituloJLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloJLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloJLabel.setText("MultiPrograms");

        esloganJLabel.setBackground(new java.awt.Color(255, 255, 255));
        esloganJLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        esloganJLabel.setForeground(new java.awt.Color(255, 255, 255));
        esloganJLabel.setText("Si puedes imaginarlo, puedes programarlo.");

        exitJLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitJLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        exitJLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitJLabel.setText(" X ");
        exitJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitJLabelMousePressed(evt);
            }
        });

        minimizeJLabel.setBackground(new java.awt.Color(255, 255, 255));
        minimizeJLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        minimizeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        minimizeJLabel.setText(" _ ");
        minimizeJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeJLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esloganJLabel)
                    .addComponent(tituloJLabel))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitJLabel)
                .addContainerGap())
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitJLabel)
                    .addComponent(minimizeJLabel))
                .addGap(29, 29, 29)
                .addComponent(tituloJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(esloganJLabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        menuJPanel.add(titleJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 140));

        masaJPanel.setBackground(new java.awt.Color(204, 204, 204));
        masaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masaJPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaJPanelMousePressed(evt);
            }
        });

        iconMasaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-peso-64.png"))); // NOI18N

        masaJLabel.setBackground(new java.awt.Color(45, 118, 235));
        masaJLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        masaJLabel.setForeground(new java.awt.Color(45, 118, 235));
        masaJLabel.setText("Masa");

        javax.swing.GroupLayout masaJPanelLayout = new javax.swing.GroupLayout(masaJPanel);
        masaJPanel.setLayout(masaJPanelLayout);
        masaJPanelLayout.setHorizontalGroup(
            masaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconMasaJLabel)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masaJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(masaJLabel)
                .addGap(33, 33, 33))
        );
        masaJPanelLayout.setVerticalGroup(
            masaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconMasaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(masaJLabel)
                .addContainerGap())
        );

        menuJPanel.add(masaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 100, 120));

        divisasJPanel.setBackground(new java.awt.Color(204, 204, 204));
        divisasJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divisasJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divisasJPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                divisasJPanelMousePressed(evt);
            }
        });

        iconDivisasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-cambio-de-divisas-60.png"))); // NOI18N

        divisasJLabel.setBackground(new java.awt.Color(45, 118, 235));
        divisasJLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        divisasJLabel.setForeground(new java.awt.Color(45, 118, 235));
        divisasJLabel.setText("Divisas");

        javax.swing.GroupLayout divisasJPanelLayout = new javax.swing.GroupLayout(divisasJPanel);
        divisasJPanel.setLayout(divisasJPanelLayout);
        divisasJPanelLayout.setHorizontalGroup(
            divisasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisasJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(divisasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(divisasJLabel)
                    .addComponent(iconDivisasJLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        divisasJPanelLayout.setVerticalGroup(
            divisasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisasJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconDivisasJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(divisasJLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        menuJPanel.add(divisasJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 120));

        temperaturaJPanel.setBackground(new java.awt.Color(204, 204, 204));
        temperaturaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                temperaturaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                temperaturaJPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                temperaturaJPanelMousePressed(evt);
            }
        });

        iconTemperaturaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-temperatura-64.png"))); // NOI18N

        temperaturaJLabel.setBackground(new java.awt.Color(45, 118, 235));
        temperaturaJLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        temperaturaJLabel.setForeground(new java.awt.Color(45, 118, 235));
        temperaturaJLabel.setText("Temperatura");

        javax.swing.GroupLayout temperaturaJPanelLayout = new javax.swing.GroupLayout(temperaturaJPanel);
        temperaturaJPanel.setLayout(temperaturaJPanelLayout);
        temperaturaJPanelLayout.setHorizontalGroup(
            temperaturaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturaJPanelLayout.createSequentialGroup()
                .addGroup(temperaturaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(temperaturaJPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconTemperaturaJLabel))
                    .addGroup(temperaturaJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(temperaturaJLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        temperaturaJPanelLayout.setVerticalGroup(
            temperaturaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturaJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconTemperaturaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperaturaJLabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        menuJPanel.add(temperaturaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 100, 120));

        longitudJPanel.setBackground(new java.awt.Color(204, 204, 204));
        longitudJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                longitudJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                longitudJPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                longitudJPanelMousePressed(evt);
            }
        });

        iconLongitudJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-longitud-64.png"))); // NOI18N

        longitudJLabel.setBackground(new java.awt.Color(45, 118, 235));
        longitudJLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        longitudJLabel.setForeground(new java.awt.Color(45, 118, 235));
        longitudJLabel.setText("Longitud");

        javax.swing.GroupLayout longitudJPanelLayout = new javax.swing.GroupLayout(longitudJPanel);
        longitudJPanel.setLayout(longitudJPanelLayout);
        longitudJPanelLayout.setHorizontalGroup(
            longitudJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(longitudJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(longitudJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longitudJLabel)
                    .addComponent(iconLongitudJLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        longitudJPanelLayout.setVerticalGroup(
            longitudJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(longitudJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconLongitudJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(longitudJLabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        menuJPanel.add(longitudJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 100, 120));

        infoJLabel.setBackground(new java.awt.Color(45, 118, 235));
        infoJLabel.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        infoJLabel.setForeground(new java.awt.Color(45, 118, 235));
        infoJLabel.setText("Realizado por Daniel López Mexico 2023");
        menuJPanel.add(infoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 310, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitJLabelMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJLabelMousePressed

    private void minimizeJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeJLabelMousePressed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_minimizeJLabelMousePressed

    private void divisasJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisasJPanelMouseEntered
        // TODO add your handling code here:
        setColor(divisasJPanel);
    }//GEN-LAST:event_divisasJPanelMouseEntered

    private void divisasJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisasJPanelMouseExited
        // TODO add your handling code here:
         resetColor(divisasJPanel);
    }//GEN-LAST:event_divisasJPanelMouseExited

    private void temperaturaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaJPanelMouseEntered
        // TODO add your handling code here:
        setColor(temperaturaJPanel);
    }//GEN-LAST:event_temperaturaJPanelMouseEntered

    private void temperaturaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaJPanelMouseExited
        // TODO add your handling code here:
        resetColor(temperaturaJPanel);
    }//GEN-LAST:event_temperaturaJPanelMouseExited

    private void longitudJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_longitudJPanelMouseEntered
        // TODO add your handling code here:
         setColor(longitudJPanel);
    }//GEN-LAST:event_longitudJPanelMouseEntered

    private void masaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaJPanelMouseEntered
        // TODO add your handling code here:
         setColor(masaJPanel);
    }//GEN-LAST:event_masaJPanelMouseEntered

    private void longitudJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_longitudJPanelMouseExited
        // TODO add your handling code here:
        resetColor(longitudJPanel);
    }//GEN-LAST:event_longitudJPanelMouseExited

    private void masaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaJPanelMouseExited
        // TODO add your handling code here:
        resetColor(masaJPanel);
    }//GEN-LAST:event_masaJPanelMouseExited

    private void divisasJPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisasJPanelMousePressed
        // TODO add your handling code here:
         new divisas().setVisible(true);
    }//GEN-LAST:event_divisasJPanelMousePressed

    private void temperaturaJPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturaJPanelMousePressed
        // TODO add your handling code here:
         new temperatura().setVisible(true);
    }//GEN-LAST:event_temperaturaJPanelMousePressed

    private void longitudJPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_longitudJPanelMousePressed
        // TODO add your handling code here:
         new longitud().setVisible(true);
    }//GEN-LAST:event_longitudJPanelMousePressed

    private void masaJPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaJPanelMousePressed
        // TODO add your handling code here:
        new masa().setVisible(true);
    }//GEN-LAST:event_masaJPanelMousePressed

    public void setColor(JPanel panel){
        panel.setBackground(new Color(115, 163, 239));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(204, 204, 204));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel divisasJLabel;
    private javax.swing.JPanel divisasJPanel;
    private javax.swing.JLabel esloganJLabel;
    private javax.swing.JLabel exitJLabel;
    private javax.swing.JLabel iconDivisasJLabel;
    private javax.swing.JLabel iconLongitudJLabel;
    private javax.swing.JLabel iconMasaJLabel;
    private javax.swing.JLabel iconTemperaturaJLabel;
    private javax.swing.JLabel infoJLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel longitudJLabel;
    private javax.swing.JPanel longitudJPanel;
    private javax.swing.JLabel masaJLabel;
    private javax.swing.JPanel masaJPanel;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JLabel minimizeJLabel;
    private javax.swing.JLabel temperaturaJLabel;
    private javax.swing.JPanel temperaturaJPanel;
    private javax.swing.JPanel titleJPanel;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
