/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multiprograms;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author efrai
 */
public class masa extends javax.swing.JFrame {

    /**
     * Creates new form divisas
     */
    public masa() {
        initComponents();
//        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloConMasaJLabel = new javax.swing.JLabel();
        iconMasaJLabel = new javax.swing.JLabel();
        unidadesMasaLeftJLabel = new javax.swing.JLabel();
        numeroMasaLeftJTextField = new javax.swing.JTextField();
        medidasMasaLeftJComboBox = new javax.swing.JComboBox<>();
        igualMasaJLabel = new javax.swing.JLabel();
        unidadesMasaRightJLabel = new javax.swing.JLabel();
        numeroMasaRightJTextField = new javax.swing.JTextField();
        medidasMasaRightJComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 235));

        tituloConMasaJLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloConMasaJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloConMasaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloConMasaJLabel.setText("Conversor de Masas");

        iconMasaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiprograms/imagenes/icons8-peso-64-blanco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tituloConMasaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(iconMasaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tituloConMasaJLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconMasaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 100));

        unidadesMasaLeftJLabel.setBackground(new java.awt.Color(45, 118, 235));
        unidadesMasaLeftJLabel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        unidadesMasaLeftJLabel.setForeground(new java.awt.Color(45, 118, 235));
        unidadesMasaLeftJLabel.setText("Unidades:");
        jPanel1.add(unidadesMasaLeftJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, 20));

        numeroMasaLeftJTextField.setBackground(new java.awt.Color(255, 255, 255));
        numeroMasaLeftJTextField.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        numeroMasaLeftJTextField.setForeground(new java.awt.Color(45, 118, 235));
        numeroMasaLeftJTextField.setText("0.0");
        numeroMasaLeftJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroMasaLeftJTextFieldActionPerformed(evt);
            }
        });
        numeroMasaLeftJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroMasaLeftJTextFieldKeyReleased(evt);
            }
        });
        jPanel1.add(numeroMasaLeftJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 220, 40));

        medidasMasaLeftJComboBox.setBackground(new java.awt.Color(45, 118, 235));
        medidasMasaLeftJComboBox.setForeground(new java.awt.Color(45, 118, 235));
        medidasMasaLeftJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonelada", "Kilogramo", "Gramo", "Miligramo" }));
        medidasMasaLeftJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidasMasaLeftJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(medidasMasaLeftJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, 40));

        igualMasaJLabel.setBackground(new java.awt.Color(45, 118, 235));
        igualMasaJLabel.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        igualMasaJLabel.setForeground(new java.awt.Color(45, 118, 235));
        igualMasaJLabel.setText(" = ");
        jPanel1.add(igualMasaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, 80));

        unidadesMasaRightJLabel.setBackground(new java.awt.Color(45, 118, 235));
        unidadesMasaRightJLabel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        unidadesMasaRightJLabel.setForeground(new java.awt.Color(45, 118, 235));
        unidadesMasaRightJLabel.setText("Unidades:");
        jPanel1.add(unidadesMasaRightJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 130, 20));

        numeroMasaRightJTextField.setBackground(new java.awt.Color(255, 255, 255));
        numeroMasaRightJTextField.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        numeroMasaRightJTextField.setForeground(new java.awt.Color(45, 118, 235));
        numeroMasaRightJTextField.setText("0.0");
        numeroMasaRightJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroMasaRightJTextFieldActionPerformed(evt);
            }
        });
        numeroMasaRightJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroMasaRightJTextFieldKeyReleased(evt);
            }
        });
        jPanel1.add(numeroMasaRightJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 220, 40));

        medidasMasaRightJComboBox.setBackground(new java.awt.Color(45, 118, 235));
        medidasMasaRightJComboBox.setForeground(new java.awt.Color(45, 118, 235));
        medidasMasaRightJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonelada", "Kilogramo", "Gramo", "Miligramo" }));
        medidasMasaRightJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidasMasaRightJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(medidasMasaRightJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroMasaLeftJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroMasaLeftJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroMasaLeftJTextFieldActionPerformed

    private void numeroMasaRightJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroMasaRightJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroMasaRightJTextFieldActionPerformed

    private void medidasMasaLeftJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidasMasaLeftJComboBoxActionPerformed
        // TODO add your handling code here:
        
         String text = "";
        text =  numeroMasaRightJTextField.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribe la unidad que desas, en el recuadro Izquierdo por favor");
        }else if(Funciones.validacionNumero(text)){
            double unidades = Double.parseDouble(text);
            String eleccion = medidasMasaLeftJComboBox.getSelectedItem().toString();
             String convertir = medidasMasaRightJComboBox.getSelectedItem().toString();
            switch(convertir){
              case "Tonelada":
                   double tonelada = Funciones.convertirTonelada(unidades, eleccion);
                    String resultado = String.valueOf( tonelada);
                    numeroMasaLeftJTextField.setText(resultado);
                  break;
              case "Kilogramo":
                     double kilogramo = Funciones.convertirKilogramo(unidades, eleccion);
                     resultado = String.valueOf(kilogramo);
                     numeroMasaLeftJTextField.setText(resultado);
                  break;


              case "Gramo":

                   double gramo = Funciones.convertirGramo(unidades, eleccion);
                     resultado = String.valueOf(gramo);
                     numeroMasaLeftJTextField.setText(resultado);
                   break;

              case "Miligramo":

                  double miligramo = Funciones.convertirMiligramo(unidades, eleccion);
                     resultado = String.valueOf(miligramo);
                     numeroMasaLeftJTextField.setText(resultado);
                   break;

            }
        }else{
               JOptionPane.showMessageDialog(null, "Solo se aceptan numeros, punto y el signo de menos");
        }
    }//GEN-LAST:event_medidasMasaLeftJComboBoxActionPerformed

    private void medidasMasaRightJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidasMasaRightJComboBoxActionPerformed
        // TODO add your handling code here:
             String text = "";
        text =  numeroMasaLeftJTextField.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribe la unidad que desas, en el recuadro Izquierdo por favor");
        }else if(Funciones.validacionNumero(text)){
            double unidades = Double.parseDouble(text);
            String eleccion = medidasMasaRightJComboBox.getSelectedItem().toString();
             String convertir = medidasMasaLeftJComboBox.getSelectedItem().toString();
            switch(convertir){
              case "Tonelada":
                   double tonelada = Funciones.convertirTonelada(unidades, eleccion);
                    String resultado = String.valueOf( tonelada);
                    numeroMasaRightJTextField.setText(resultado);
                  break;
              case "Kilogramo":
                     double kilogramo = Funciones.convertirKilogramo(unidades, eleccion);
                     resultado = String.valueOf(kilogramo);
                     numeroMasaRightJTextField.setText(resultado);
                  break;


              case "Gramo":

                   double gramo = Funciones.convertirGramo(unidades, eleccion);
                     resultado = String.valueOf(gramo);
                     numeroMasaRightJTextField.setText(resultado);
                   break;

              case "Miligramo":

                  double miligramo = Funciones.convertirMiligramo(unidades, eleccion);
                     resultado = String.valueOf(miligramo);
                     numeroMasaRightJTextField.setText(resultado);
                   break;

            }
        }else{
               JOptionPane.showMessageDialog(null, "Solo se aceptan numeros, punto y el signo de menos");
        }
    }//GEN-LAST:event_medidasMasaRightJComboBoxActionPerformed

    private void numeroMasaLeftJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroMasaLeftJTextFieldKeyReleased
        // TODO add your handling code here:
          String text = "";
        text =  numeroMasaLeftJTextField.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribe la unidad que desas, en el recuadro Izquierdo por favor");
        }else if(Funciones.validacionNumero(text)){
            double unidades = Double.parseDouble(text);
            String eleccion = medidasMasaLeftJComboBox.getSelectedItem().toString();
             String convertir = medidasMasaRightJComboBox.getSelectedItem().toString();
            switch(eleccion){
              case "Tonelada":
                   double tonelada = Funciones.convertirTonelada(unidades, convertir);
                    String resultado = String.valueOf( tonelada);
                    numeroMasaRightJTextField.setText(resultado);
                  break;
              case "Kilogramo":
                     double kilogramo = Funciones.convertirKilogramo(unidades, convertir);
                     resultado = String.valueOf(kilogramo);
                     numeroMasaRightJTextField.setText(resultado);
                  break;


              case "Gramo":

                   double gramo = Funciones.convertirGramo(unidades, convertir);
                     resultado = String.valueOf(gramo);
                     numeroMasaRightJTextField.setText(resultado);
                   break;

              case "Miligramo":

                  double miligramo = Funciones.convertirMiligramo(unidades, convertir);
                     resultado = String.valueOf(miligramo);
                     numeroMasaRightJTextField.setText(resultado);
                   break;

            }
        }else{
               JOptionPane.showMessageDialog(null, "Solo se aceptan numeros, punto y el signo de menos");
        }
    }//GEN-LAST:event_numeroMasaLeftJTextFieldKeyReleased

    private void numeroMasaRightJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroMasaRightJTextFieldKeyReleased
        // TODO add your handling code here:
                  String text = "";
        text =  numeroMasaRightJTextField.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribe la unidad que desas, en el recuadro Izquierdo por favor");
        }else if(Funciones.validacionNumero(text)){
            double unidades = Double.parseDouble(text);
            String eleccion = medidasMasaRightJComboBox.getSelectedItem().toString();
             String convertir = medidasMasaLeftJComboBox.getSelectedItem().toString();
            switch(eleccion){
              case "Tonelada":
                   double tonelada = Funciones.convertirTonelada(unidades, convertir);
                    String resultado = String.valueOf( tonelada);
                    numeroMasaLeftJTextField.setText(resultado);
                  break;
              case "Kilogramo":
                     double kilogramo = Funciones.convertirKilogramo(unidades, convertir);
                     resultado = String.valueOf(kilogramo);
                     numeroMasaLeftJTextField.setText(resultado);
                  break;


              case "Gramo":

                   double gramo = Funciones.convertirGramo(unidades, convertir);
                     resultado = String.valueOf(gramo);
                     numeroMasaLeftJTextField.setText(resultado);
                   break;

              case "Miligramo":

                  double miligramo = Funciones.convertirMiligramo(unidades, convertir);
                     resultado = String.valueOf(miligramo);
                     numeroMasaLeftJTextField.setText(resultado);
                   break;

            }
        }else{
               JOptionPane.showMessageDialog(null, "Solo se aceptan numeros, punto y el signo de menos");
        }
    }//GEN-LAST:event_numeroMasaRightJTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconMasaJLabel;
    private javax.swing.JLabel igualMasaJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> medidasMasaLeftJComboBox;
    private javax.swing.JComboBox<String> medidasMasaRightJComboBox;
    private javax.swing.JTextField numeroMasaLeftJTextField;
    private javax.swing.JTextField numeroMasaRightJTextField;
    private javax.swing.JLabel tituloConMasaJLabel;
    private javax.swing.JLabel unidadesMasaLeftJLabel;
    private javax.swing.JLabel unidadesMasaRightJLabel;
    // End of variables declaration//GEN-END:variables
}
